AvansFysioOpdrachtIndividueel/Controllers/PatientDossierModelsController.cs
using AvansFysioOpdrachtIndividueel.Models;
using Core.Domain.Domain;
using Core.DomainServices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AvansFysioOpdrachtIndividueel.Controllers
{
    public class PatientDossierModelsController : Controller
    {

        private readonly IPatientRepo _patientRepo;
        private readonly ITherapistRepo _therapistRepo;
        private readonly IAsyncRepo<DiagnosisModel> _diagnosisRepo;

        public PatientDossierModelsController(IPatientRepo patientRepo, ITherapistRepo therapistRepo, IAsyncRepo<DiagnosisModel> diagnosisRepo)
        {
            _patientRepo = patientRepo;
            _therapistRepo = therapistRepo;
            _diagnosisRepo = diagnosisRepo;
        }

        // GET: PatientDossierModelsController
        public ActionResult Index()
        {
            return View();
        }

        // GET: PatientDossierModelsController/Details/5
        public ActionResult Details(int id)
        {

            return View();
        }

        // GET: PatientDossierModelsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PatientDossierModelsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PatientDossierModelsController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            return View(await FillPatientDossierDetailsViewModel(id));
        }

        // POST: PatientDossierModelsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, PatientDossierDetailsViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                PatientModel patient = _patientRepo.Get(id);

                patient.PatientDossier.Therapist = _therapistRepo.Get(viewModel.TherapistId);
                patient.PatientDossier.IntakeDoneBy = _therapistRepo.Get(viewModel.IntakeDoneById);
                patient.PatientDossier.IntakeSupervisedBy = _therapistRepo.Get(viewModel.SupervisedById);

                patient.PatientDossier.PlannedDate = viewModel.PlannedDate;
                patient.PatientDossier.DueDate = viewModel.DueDate;
                patient.PatientDossier.IssueDescription = viewModel.IssueDescription;
                patient.PatientDossier.DiagnosisCode = new DiagnosisModel
                {
                    CodeAndDescription = viewModel.DiagnosisCode
                };
                _patientRepo.Update(patient, id);

                return RedirectToAction("Details", controllerName: "PatientModels", new { id });
            }
            else
            {                
                return View(await FillPatientDossierDetailsViewModel(id));
            }
        }

        // GET: PatientDossierModelsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PatientDossierModelsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public async Task<PatientDossierDetailsViewModel> FillPatientDossierDetailsViewModel(int id)
        {
            var patientModel = _patientRepo.Get(id);
            
            PatientDossierDetailsViewModel model = new PatientDossierDetailsViewModel
            {
                Name = patientModel.Name,
                Id = id,
                IssueDescription = patientModel.PatientDossier.IssueDescription,
                //DiagnosisCode = patientModel.PatientDossier.DiagnosisCode.CodeAndDescription,
                DueDate = patientModel.PatientDossier.DueDate,
                PlannedDate = patientModel.PatientDossier.PlannedDate,
                Therapist = patientModel.PatientDossier.Therapist,
                IntakeSupervisedBy = patientModel.PatientDossier.IntakeSupervisedBy,
                IntakeDoneBy = patientModel.PatientDossier.IntakeDoneBy,
                Therapists = _therapistRepo.GetTherapists()
            };
            var result = await _diagnosisRepo.Get();
            model.DiagnosisCodes = new List<SelectListItem>();
            // model.DiagnosisCodes.Add(new SelectListitem());
            foreach (var item in result)
            {
                model.DiagnosisCodes.Add(new SelectListItem(item.CodeAndDescription,item.CodeAndDescription));
            }
            
            if(patientModel.PatientDossier.DiagnosisCode != null)
            {
                model.DiagnosisCode = patientModel.PatientDossier.DiagnosisCode.CodeAndDescription;
            }

            return model;
        }
    }
}

AvansFysioOpdrachtIndividueel/Controllers/PatientTreatmentModelsController.cs
using AvansFysioOpdrachtIndividueel.Models;
using Core.Domain.Domain;
using Core.DomainServices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AvansFysioOpdrachtIndividueel.Controllers
{
    public class PatientTreatmentModelsController : Controller
    {
        private readonly IPatientRepo _patientRepo;
        private readonly ITherapistRepo _therapistRepo;
        private readonly ITreatmentManager _treatmentManager;
        private readonly IVektisRepo _vektisRepo;
        private readonly UserManager<IdentityUser> _userManager;
        public PatientTreatmentModelsController(IPatientRepo patientRepo, ITherapistRepo therapistRepo, ITreatmentManager treatmentManager, IVektisRepo vektisRepo, UserManager<IdentityUser> userManager)
        {
            _patientRepo = patientRepo;
            _therapistRepo = therapistRepo;
            _treatmentManager = treatmentManager;
            _vektisRepo = vektisRepo;
            _userManager = userManager;
        }

        // GET: PatientTreatmentModelsController
        public ActionResult Index()
        {
            return View();
        }

        // GET: PatientTreatmentModelsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PatientTreatmentModelsController/Create/5
        public async Task<ActionResult> Create(int id)
        {
            TreatmentFormViewModel treatmentFormViewModel = new TreatmentFormViewModel();

            treatmentFormViewModel.Therapists = _therapistRepo.GetTherapists();
            treatmentFormViewModel.VektisTypes = await _vektisRepo.GetVekti();
            treatmentFormViewModel.Id = id;

            return View(treatmentFormViewModel);
        }

        // POST: PatientTreatmentModelsController/Create/5
        [HttpPost]
        [ValidateAntiForgeryToken]
  
        public async Task<ActionResult> Create(TreatmentFormViewModel collection, int id)
        {
            if (!ModelState.IsValid)
            {
                collection.Therapists = _therapistRepo.GetTherapists();
                collection.VektisTypes = await _vektisRepo.GetVekti();
                return View(collection);
            }

            if (!_treatmentManager.IsWithinAllowedTreatmentAmount(id, collection.Treatment))
            {
                return await SendBackToView("Je mag niet meer behandelingen aanmaken dan in je behandelplan staat.", collection);
            }

            PatientModel patientModel = _patientRepo.Get(id);
            // check if the patient has been registered.

            var userResult = await _userManager.FindByEmailAsync(patientModel.Email);

            if(userResult == null)
            {
                return await SendBackToView("De gebruik moet geregistreerd zijn voor een behandeling toegevoegd mag worden!", collection);
            }
            // Fill in the end of the treatment datetime by taking the treatmentplan TimeOfTreatment in minutes and adding it to the starting treatment time.
            collection.Treatment.TreatmentUntil = collection.Treatment.TreatmentTime.AddMinutes(patientModel.PatientDossier.TreatmentPlan.TimeOfTreatment);

            if (!_treatmentManager.IsTherapistAvailable(collection.TherapyDoneById, collection.Treatment))
            {
                return await SendBackToView("De therapeut is niet beschikbaar op deze tijd.", collection);
            }

            // get the vektis type 
            var result = await _vektisRepo.Get(collection.Treatment.VektisType.Id);
            // if it needs a description, check if the collection has a description
            if (result.NeedsDescription)
            {
                // if there is no description send back an error
                try
                {
                    if (collection.Treatment.Description.Length < 0)
                    {
                        return await SendBackToView("Dit vektysType heeft een beschrijving nodig", collection);
                    }
                }
                catch(Exception ex)
                {
                    return await SendBackToView("Dit vektysType heeft een beschrijving nodig", collection);
                }
            }
            collection.Treatment.VektisType = new VektisModel{
                Value = result.Value,
                NeedsDescription = result.NeedsDescription
            };
            collection.Treatment.TreatmentDoneBy = _therapistRepo.Get(collection.TherapyDoneById);

            patientModel.PatientDossier.Treatments.Add(collection.Treatment);

            _patientRepo.Update(patientModel, id);

            return RedirectToAction("Details", "PatientModels", new { id });
        }

        // GET: PatientTreatmentModelsController/Edit/5
        public ActionResult Edit(int id, int treatmentId)
        {
            TreatmentFormViewModel treatmentFormViewModel = new TreatmentFormViewModel();

            treatmentFormViewModel.Therapists = _therapistRepo.GetTherapists();
            treatmentFormViewModel.Id = id;
            treatmentFormViewModel.Treatment = _patientRepo.Get(id).PatientDossier.Treatments.Find(t => t.Id == treatmentId);

            return View(treatmentFormViewModel);
        }

        // POST: PatientTreatmentModelsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, int treatmentId, TreatmentFormViewModel collection)
        {
            PatientModel patient = _patientRepo.Get(id);
            var treatment = patient.PatientDossier.Treatments.Find(t => t.Id == treatmentId);

            if (!ModelState.IsValid)
            {
                collection.Therapists = _therapistRepo.GetTherapists();
                collection.Id = id;
                collection.Treatment = treatment;
                return View(collection);
            }
            
            if (DateTime.Now.Subtract(treatment.TreatmentTime).TotalHours > -24)
            { 
                return await SendBackToView("Je kan een behandeling niet 24 van te voren bewerken of verwijderen.", collection);
            }

            // get the vektis type 
            var result = await _vektisRepo.Get(collection.Treatment.VektisType.Id);
            // if it needs a description, check if the collection has a description
            if (result.NeedsDescription)
            {
                // if there is no description send back an error
                if (collection.Treatment.Description.Length < 0)
                {
                    return await SendBackToView("Dit vektysType heeft een beschrijving nodig", collection);
                }
            }
            collection.Treatment.VektisType = result;

            patient.PatientDossier.Treatments.Remove(treatment);

            treatment = collection.Treatment;
            treatment.TreatmentDoneBy = _therapistRepo.Get(collection.TherapyDoneById);

            patient.PatientDossier.Treatments.Add(treatment);

            _patientRepo.Update(patient, id);

            return RedirectToAction("Details", "PatientModels", new { id });
        }
        public ActionResult Delete(int id, int treatmentId)
        {
            
            PatientModel patient = _patientRepo.Get(id);
            
            var result = patient.PatientDossier.Treatments.Find(t => t.Id == treatmentId);
            if (DateTime.Now.Subtract(result.TreatmentTime).TotalHours > -24)
            {
                ModelState.AddModelError("Delete", "Je kan een behandeling niet 24 van te voren bewerken of verwijderen.");
                return RedirectToAction("Details", "PatientModels", new { id });
            }

            patient.PatientDossier.Treatments.Remove(result);
            _patientRepo.Update(patient, id);
            return RedirectToAction("Details", "PatientModels", new { id });
            
        }

        public async Task<ViewResult> SendBackToView(string errorMessage, TreatmentFormViewModel collection)
        {
            ModelState.AddModelError(string.Empty, errorMessage);
            collection.Therapists = _therapistRepo.GetTherapists();
            collection.VektisType = new VektisModel {
                Id = collection.Treatment.VektisType.Id,
                NeedsDescription = collection.Treatment.VektisType.NeedsDescription,
                Value = collection.Treatment.VektisType.Value
            };
            collection.VektisTypes = await _vektisRepo.GetVekti();
            return View(collection);
        }
        //public IActionResult AddTreatment(PatientDossierViewModel model, int id)
        //{
        //    PatientModel patientModel = _patientRepo.Get(id);
        //    if (!ModelState.IsValid)
        //    {
        //        return View("Details", FillPatientDossierViewModel(id));
        //    }
        //    if (patientModel.PatientDossier.Treatments == null)
        //    {
        //        patientModel.PatientDossier.Treatments = new List<TreatmentModel>();
        //    }
        //    if (CheckIfTeacher(model.TreatmentDoneById) == true)
        //    {
        //        model.TreatmentModel.TreatmentDoneBy = _teacherRepo.Get(model.TreatmentDoneById);
        //    }
        //    else
        //    {
        //        model.TreatmentModel.TreatmentDoneBy = _studentRepo.Get(model.TreatmentDoneById);
        //    }

        //    patientModel.PatientDossier.Treatments.Add(model.TreatmentModel);

        //    _patientRepo.Update(patientModel, id);

        //    // TODO:: find out if there is a better way to do this
        //    return RedirectToAction("Details", new { id });
        //}
        //// TODO:: Maybe refactor to different controller
        //public IActionResult RemoveTreatment(int dossierId, int treatmentId, int id)
        //{

AvansFysioOpdrachtIndividueel/Views/PatientModels/Create.cshtml
@model PatientModel

@{
    ViewData["Title"] = "Create";
}

<h4>Voeg een patient toe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
                <div asp-validation-summary="All"></div>
                <div class="form-group">
                    <label asp-for="Name">Jouw naam:</label>
                    <input class="form-control" asp-for="Name" />
                </div>

                <div class="form-group">
                    <label asp-for="Email">Jouw Email:</label>
                    <input class="form-control" asp-for="Email" />
                </div>

                <div class="form-group">
                    <label asp-for="DateOfBirth">Jouw geboortedatum:</label>
                    <input class="form-control" asp-for="DateOfBirth" />
                </div>

                <div class="form-group">
                    <label asp-for="PatientNumber">Patientnummer::</label>
                    <input class="form-control" asp-for="PatientNumber" />
                </div>

               <div class="form-group">
                    <label asp-for="Gender">Geslacht:</label>
                    <input class="form-control" asp-for="Gender" />
                </div>

                <button class="btn btn-primary" type="submit">Client toevoegen</button>
            </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AvansFysioOpdrachtIndividueel/Views/PatientModels/Delete.cshtml
@model AvansFysioOpdrachtIndividueel.Models.PatientModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Verwijder @Model.Name</h1>

<h3>Wil je deze patient echt verwijderen?</h3>
<div>
    <h4>PatientModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatientNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatientNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AvansFysioOpdrachtIndividueel/Views/PatientModels/Details.cshtml
@model AvansFysioOpdrachtIndividueel.Models.PatientDossierViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <div class="row">
        <div class="patient-info">
            <h1>@Model.PatientModel.Name's  overzicht:</h1>
            <hr />
            <ul class="list-group">
                <li class="list-group-item">Email: @Model.PatientModel.Email</li>
                <li class="list-group-item">Geboorte datum: @Model.PatientModel.DateOfBirth</li>
                <li class="list-group-item">Geslacht: @Model.PatientModel.Gender</li>
            </ul>
        </div>
    </div>
    @if (Model.PatientModel.PatientDossier.Therapist != null)
    {
        <div class="row">
            <div class="row patient-dossier col">
                <h2>Patienten dossier van @Model.PatientModel.Name</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Geplande start datum</th>
                            <th>Geplande einddatum</th>
                            <th>Therapeut</th>
                            <th>Diagnose code</th>
                            <th>Intake gedaan door</th>
                            <th>Intake bijgewoond door</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Model.PatientModel.PatientDossier.PlannedDate</td>
                            <td>@Model.PatientModel.PatientDossier.DueDate</td>
                            <td>@Model.PatientModel.PatientDossier.Therapist.Name</td>
                            <td>@Model.PatientModel.PatientDossier.DiagnosisCode.CodeAndDescription</td>
                            <td>@Model.PatientModel.PatientDossier.IntakeDoneBy.Name</td>
                            <td>@Model.PatientModel.PatientDossier.IntakeSupervisedBy.Name</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="patient-treatmentplan col">
                @if (Model.PatientModel.PatientDossier.TreatmentPlan != null)
                {
                    <h2>Behandelplan:</h2>
                    <ul class="list-group">
                        <li class="list-group-item">-Maximaal @Model.PatientModel.PatientDossier.TreatmentPlan.AmountOfTreaments behandelingen per week.</li>
                        <li class="list-group-item">-Maximaal @Model.PatientModel.PatientDossier.TreatmentPlan.TimeOfTreatment behandeltijd in minuten.</li>
                    </ul>
                }
            </div>
        </div>
        <div class="row justify-content-between create-edit-buttons">
            @if (@Model.PatientModel.PatientDossier != null)
            {
                <a class="col-3 btn btn-primary" asp-action="Edit" asp-controller="PatientDossierModels" asp-route-id="@Model.PatientModel.Id">Bewerk patientendossier.</a>
                @if (@Model.PatientModel.PatientDossier.TreatmentPlan != null)
                {
                    <a class="col-3 btn btn-primary" asp-action="Edit" asp-controller="PatientTreatmentPlanModels" asp-route-id="@Model.PatientModel.Id">Bewerk dit behandelplan.</a>
                }
                else
                {
                    <a class="col-3 btn btn-primary" asp-action="Create" asp-controller="PatientTreatmentPlanModels" asp-route-id="@Model.PatientModel.Id">Maak een behandelplan aan.</a>
                }
            }
        </div>
        <div class="patient-treatments row">
            @if (Model.PatientModel.PatientDossier.Treatments.Count > 0)
            {
                <h2>Behandelingen van @Model.PatientModel.Name</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Complicaties</th>
                            <th>Bevind de behandeling in een behandelkamer?</th>
                            <th>Behandeldatum</th>
                            <th>Beschrijving</th>
                            <th>VektisType</th>
                            <th>Behandeling gedaan door</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var treatment in Model.PatientModel.PatientDossier.Treatments)
                        {
                            <tr>
                                <td>@treatment.Complications</td>
                                <td>@treatment.TreatmentRoomOrTrainingRoom</td>
                                <td>@treatment.TreatmentTime</td>
                                <td>@treatment.Description</td>
                                <td>@treatment.VektisType.Value</td>
                                <td>@treatment.TreatmentDoneBy.Name</td>
                                <td><a asp-action="Delete" class="btn btn-primary" asp-controller="PatientTreatmentModels" asp-route-id="@Model.PatientModel.Id" asp-route-treatmentId="@treatment.Id">Verwijder behandeling </a> </td>
                                <td><a asp-action="Edit" class="btn btn-primary" asp-controller="PatientTreatmentModels" asp-route-id="@Model.PatientModel.Id" asp-route-treatmentId="@treatment.Id">Bewerk behandeling</a> </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <h2>Hier komen patient behandelingen</h2>
            }

        </div>
        <div class="row">
            <a class="btn btn-primary" asp-action="Create" asp-controller="PatientTreatmentModels" asp-route-id="@Model.PatientModel.Id">Voeg een treatment toe</a>
        </div>
        <div class="row extra-comments">
            @if (Model.PatientModel.PatientDossier.ExtraComments != null)
            {
                <h2>Extra opmerkingen</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Opmerking</th>
                            <th>Aangemaakt op:</th>
                            <th>Gemaakt door:</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var comment in Model.PatientModel.PatientDossier.ExtraComments)
                        {
                            <tr>
                                <td>@comment.Id</td>
                                <td>@comment.Comment</td>
                                <td>@comment.TimeOfCreation</td>
                                <td>@comment.CommentMadeBy.Name</td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <h2>Hier komen extra opmerkingen</h2>
            }

            <form asp-action="AddComment" asp-route-id="@Model.PatientModel.Id" method="post">
                <div asp-validation-summary="All"></div>
                <div class="form-group">
                    <label asp-for="@Model.Comment.Comment">Opmerking:</label>
                    <input class="form-control" asp-for="@Model.Comment.Comment" />
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Comment.CommentVisibleForPatient">Moet de opmerking zichtbaar zijn voor de patient?:</label>
                    <input class="form-control" asp-for="@Model.Comment.CommentVisibleForPatient" />
                </div>
                <button class="btn btn-primary" type="submit">Opmerking toevoegen</button>
            </form>
        </div>
    }
    else
    {
        <div class="row">
            <a class="col-3 btn btn-primary" asp-action="Edit" asp-controller="PatientDossierModels" asp-route-id="@Model.PatientModel.Id">Bewerk @Model.PatientModel.Name's dossier.</a>
        </div>
    }
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PatientModel.Id">Edit</a>
    <a asp-action="Index">Back to List</a>
</div>

AvansFysioOpdrachtIndividueel/Views/PatientModels/Edit.cshtml
@model AvansFysioOpdrachtIndividueel.Models.PatientModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PatientModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PatientNumber" class="control-label"></label>
                <input asp-for="PatientNumber" class="form-control" />
                <span asp-validation-for="PatientNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AvansFysioOpdrachtIndividueel/Views/PatientModels/Index.cshtml
@model IEnumerable<AvansFysioOpdrachtIndividueel.Models.PatientModel>

@{
    ViewData["Title"] = "Index";
}
<h1>Patient overzicht</h1>
<p>
    <a asp-action="Create">Voeg een nieuwe Patient toe</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PatientNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PatientNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>