AvansFysioOpdrachtIndividueel/Controllers/PatientModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using AvansFysioOpdrachtIndividueel.Models;
using Microsoft.AspNetCore.Authorization;
using Core.Domain.Domain;
using Core.DomainServices;
using Microsoft.AspNetCore.Identity;
using Core.Data;

namespace AvansFysioOpdrachtIndividueel.Controllers
{
    public class PatientModelsController : Controller
    {
        private readonly IPatientRepo _patientRepo;
        private readonly ITherapistRepo _therapistRepo;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IRepo<PersonModel> _personRepo;
        public PatientModelsController( IPatientRepo repo, ITherapistRepo therapistRepo, UserManager<IdentityUser> userManager, IRepo<PersonModel> personRepo)
        {
            _patientRepo = repo;
            _therapistRepo = therapistRepo;
            _userManager = userManager;
            _personRepo = personRepo;
        }

        // GET: PatientModels
        [Authorize(Roles = "Patient,Therapist")]
        public IActionResult Index()
        {
            return View(_patientRepo.Get().ToList());
        }
        // GET: PatientModels/Details/5
        public IActionResult Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            PatientDossierViewModel patientModel = FillPatientDossierViewModel(id);
            if(patientModel == null)
            {
                return NotFound();
            }

            return View(patientModel);
        }

        // GET: PatientModels/Create
        public IActionResult Create()
        {
            return View();
        }
        // POST: PatientModels/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("PatientNumber,DateOfBirth,Gender,Name,Email")] PatientModel patientModel)
        {
            if (ModelState.IsValid)
            {
                patientModel.PatientDossier = new PatientDossierModel();
                patientModel.PatientDossier.ExtraComments = new List<CommentModel>();

                    if (_personRepo.Get().Exists(t => t?.Email == patientModel.Email))
                    {
                        ModelState.AddModelError(String.Empty, "De email bestaat al.");
                        return View();
                    }

                    _patientRepo.Create(patientModel);
                    return RedirectToAction(nameof(Index));

                // if it fails that means there are no persons in the database
            }
            return View(patientModel);
        }

        // GET: PatientModels/Edit/5
        public IActionResult Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var patientModel = _patientRepo.Get(id);

            if (patientModel == null)
            {
                return NotFound();
            }
            return View(patientModel);
        }

        // POST: PatientModels/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PatientNumber,DateOfBirth,Gender,Id,Name,Email")] PatientModel patientModel)
        {
            if (id != patientModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _patientRepo.Update(patientModel,id);
                return RedirectToAction(nameof(Index));
            }
            return View(patientModel);
        }

        // GET: PatientModels/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patientModel = _patientRepo.Get(id);
            if (patientModel == null)
            {
                return NotFound();
            }

            return View(patientModel);
        }
        // POST: PatientModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            _patientRepo.Remove(id);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> AddComment(int id,PatientDossierViewModel patientDossierViewModel)
        {
            if (ModelState.IsValid)
            {
                PatientModel patientModel = _patientRepo.Get(id);

                // Gets and sets the currently logged in user to the author.
                var user = await _userManager.GetUserAsync(HttpContext.User);
                patientDossierViewModel.Comment.CommentMadeBy = _therapistRepo.Get().Where(p => p?.Email == user?.UserName).FirstOrDefault();

                patientDossierViewModel.Comment.TimeOfCreation = DateTime.Now;
                patientModel.PatientDossier.ExtraComments.Add(patientDossierViewModel.Comment);

                _patientRepo.UpdatePatientDossier(patientModel, id);

                return RedirectToAction("Details", new { id });
            }
            else
            {
                // Need to return view, otherwise modelstate gets lost
                return View("Details", FillPatientDossierViewModel(id));
            }
           
        }

        public PatientDossierViewModel FillPatientDossierViewModel(int id)
        {
            PatientDossierViewModel patientModel = new();
            patientModel.PatientModel = _patientRepo.Get(id);
            // Make the selectitems only therapists. 
            // For this we need a therapist repo
            // TODO:: Find a better way to convert these 2 lists into personmodels..

            patientModel.Therapists = _therapistRepo.GetTherapists();

            try
            {
                patientModel.TreatmentModels = _patientRepo.Get(id).PatientDossier.Treatments.ToList();
                
            }
            catch (Exception)
            {

            }
            return patientModel;
        }
    }
}

AvansFysioOpdrachtIndividueel/Controllers/TherapistModelsController.cs
using AvansFysioOpdrachtIndividueel.Models;
using Core.DomainServices;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AvansFysioOpdrachtIndividueel.Controllers
{
    public class TherapistModelsController : Controller
    {
        private readonly IPatientRepo _patientRepo;
        private readonly ITherapistRepo _therapistRepo;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        public TherapistModelsController(IPatientRepo repo, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ITherapistRepo therapistRepo)
        {
            _patientRepo = repo;
            _userManager = userManager;
            _signInManager = signInManager;
            _therapistRepo = therapistRepo;
        }
        // GET: TherapistModelsController
        [Authorize(Roles = "Therapist")]
        public async Task<ActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            if (user == null)
            {
                return NotFound();
            }

            // Get the therapist that belongs to the user.
            PersonModel therapist = _therapistRepo.Get().Where(t => t.Email == user.Email).FirstOrDefault();

            List<PatientModel> patients = _patientRepo.Get();
            List<TreatmentViewModel> viewModel = new List<TreatmentViewModel>();

            // now get the therapist.
            foreach (PatientModel pat in patients)
            {
                // Find all treatments that belong to this therapist and that have a treatment today.
                List<TreatmentModel> treatmentModels = pat.PatientDossier.Treatments.
                    Where(t => t.TreatmentDoneBy.Id == therapist.Id && t.TreatmentTime.Date == DateTime.Today.Date).ToList();
                foreach (var treatment in treatmentModels)
                {
                    viewModel.Add(new TreatmentViewModel
                    {
                        Name = pat.Name,
                        treatment = treatment
                    });
                }
            }
            
            return View(viewModel.OrderBy(t => t.treatment.TreatmentTime));
        }

        // The ID here should be the ID of the therapist.
        // GET: TherapistModelsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TherapistModelsController/Create    
        public ActionResult Create()
        {
            return View();
        }

        // POST: TherapistModelsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TherapistModelsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TherapistModelsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TherapistModelsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TherapistModelsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AvansFysioOpdrachtIndividueel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AvansFysioOpdrachtIndividueel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AvansFysioOpdrachtIndividueel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PatientModels" asp-action="Index">Patiënten</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TherapistModels" asp-action="Index">Therapuiten overzicht</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Log in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register">Registreer</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Log uit</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @await Component.InvokeAsync("PatientCount")
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AvansFysioOpdrachtIndividueel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>